### ISSUE TITLE
Bug: When campaign_target's OpenStates uid is `us_state:openstates:~not available~`, it is sometimes incorrectly included in a campaign

### ISSUE THREAD

**Issue by timothyasp** [OpenSourceActivismTech/call-power#101]
First off - thanks a ton for maintaining this project, it's been a huge help to us and our organization Repair.org.

This bug was brought to my attention after one of our community organizers noticed that callpower was directing him to call a MA senator when targeting his zipcode in MN.

I've been able to reproduce the issue as follows:

When a record has a `uid` as `us_state:openstates:~not available~`, it is included in other states campaign targets when it shouldn't be.  

Some example records from our DB:

`campaign_target` record:
https://d.pr/i/NFjeI3

`campaign_campaign` record:
`7,2017-02-01 00:23:42,Washington,state,WA,both,location,in-order,f,null,2,postal,{"script_display": "replace", "custom_css": "https://wyoming.repair.org/css/callpower.css", "type": "iframe", "script": "Tell them you support The Fair Repair Act. Tell them why repair is important to you."},us,en,,,f,f,t`

If I remove the uid from the campaign target row, everything works as expected.  If I set a `campaign_target records' UID to `us_state:openstates:~not available~`, it starts being included in a number of campaigns where it shouldn't be.

Let me know if that was clear enough - I've tried digging into the code and it seems like it might be an issue with OpenStates returning `~not available~` for some new, freshman reps and the queries are returning them for whatever reason.  But that's just a guess on my part.

Happy to provide DB dumps privately if needed.

**Comment by jlev** [comment]
Interesting bug! Thanks for reporting. Just to clarify, are you only seeing the rogue target appearing in other states, or in other types of campaigns as well?

From a quick look at the code in https://github.com/OpenSourceActivismTech/call-power/blob/master/call_server/political_data/countries/us.py#L448 it looks like it should be storing exactly what we get from OpenStates. I know their API has changed recently, and there may be adjustments we need to make on our end.

**Comment by timothyasp** [comment]
> Interesting bug! Thanks for reporting. Just to clarify, are you only seeing the rogue target appearing in other states, or in other types of campaigns as well?

 Not 100% sure what you're asking - we're only running state legislator campaigns.  Wish I could provide more detail.

**Comment by kwiens** [comment]
Bump on this @jlev — we've got the tool disabled while we try to figure it out, and would love to get operational again.

**Comment by jlev** [comment]
The problem is that our upstream data provider switched their ID format, and are returning the string "~not available~" for newly elected officials starting in 2019. https://github.com/openstates/openstates/issues/2792

We cache the API results, and as you've noticed, if you have multiple ones with the same cache key they'll leak across state campaigns...

I'll have to update our code to use their v2 API which uses GraphQL, instead of their simpler v1.

**Comment by jlev** [comment]
There is now a WIP branch at [feature/upgrade-openstates](https://github.com/OpenSourceActivismTech/call-power/tree/feature/upgrade-openstates)

**Comment by jlev** [comment]
@timothyasp and @kwiens, this is now working in my local and demo environments for existing legislators in my area.

If you can verify it works for your affected locations (Osseo, MN 55311 per your db record), I can merge into master and upgrade my hosted instances/.

**Comment by timothyasp** [comment]
@jlev Whoo! I'll get that merged in and tested.

**Comment by timothyasp** [comment]
Just went through and tested 55369 and it's working as expected! Thanks @jlev

One question - if a legislator doesn't have an ID, are they being excluded from all calls?

**Comment by jlev** [comment]
We now hit the OpenStates API for the state legislators who represent a latlon, and add their contact info to our cache to connect users to them. I'm not applying a filter to check for matching IDs at the sorting step, but I do double check the legislator's state and chamber at https://github.com/OpenSourceActivismTech/call-power/blob/master/call_server/political_data/countries/us.py#L214

**Comment by kwiens** [comment]
Awesome, thanks so much @jlev! We were able to turn the tool back on. Now on to our next hearing!
