### ISSUE TITLE
Cannot deploy this app anywhere

### ISSUE THREAD

**Issue by Hayyk** [OpenSourceActivismTech/call-power#103]
Hi,

I've problem deploying this app anywhere. Actually the goal is to have this either running in docker container or on Heroku. While deploying to Heroku, the build fails. You can find the build log attached
[heroku_deply_log.txt](https://github.com/OpenSourceActivismTech/call-power/files/2966160/heroku_deply_log.txt)

While using docker (after changing the base image from ubuntu to ubuntu:xenial - coz there is a commit that doesn't exist in your repo but exists in EFForg's one) Image build is successfull but I'm facing error running container (error is the same when trying to deploy locally). Here is the build log: 
[docker_build_log2.txt](https://github.com/OpenSourceActivismTech/call-power/files/2966407/docker_build_log2.txt)

Any help appreciated

**Comment by jlev** [comment]
Hi @Hayyk it looks like this may be an issue with uWSGI
https://github.com/unbit/uwsgi/issues/1395

 I deploy this app to Heroku regularly, and EFF uses Docker.

Try upgrading your fork's requirements/production.txt to `uWSGI==2.0.15`?

I'm in the middle of another building another set of features, but can merge that upgrade when I release v1.5

**Comment by jlev** [comment]
To start the server locally, as it looks like you were able to do using the Docker build, you'll need to first create the database tables with `python manager.py migrate up`

**Comment by Hayyk** [comment]
Hi @jlev Thanks for reply.
Yes, I tried to run python manager.py migrate up when deploying to local server. and when running docker-compose up it also exits in that steps and throws an error. it can be found in the [file](https://github.com/OpenSourceActivismTech/call-power/files/2966407/docker_build_log2.txt) I've attached in the issue description
For heroku, chaning uWSGI==2.0.15 leaded app to be deployed, but I'm getting "Internal Server Error"

**Comment by jlev** [comment]
Found an issue that was causing migrations to error out on first run.

Apologies, it's been awhile since I've set up a new instance of this tool. It's been running stably for a half-dozen organizations for three years.

If you have other questions about it's use, please feel free to email me at info@callpower.org

**Comment by Hayyk** [comment]
@jlev Thanks a lot,
 this worked.
not to spam here about usage, I've sent you an email as you mentioned above.
