### ISSUE TITLE
OpenStates search for legislators last name broken

### ISSUE THREAD

**Issue by jlev** [OpenSourceActivismTech/call-power#106]
Currently returns all members of the chamber, not filtering on name. Needs to be upgraded to GraphQL in any case, as people elected in 2019 have \~not_available\~ as their leg_id.

**Comment by jlev** [comment]
Determined two queries necessary for this at https://discourse.openstates.org/t/querying-legislators-by-state-and-name/361

Either chain them, or figure out how to nest or subquery with GraphQL...

**Comment by jlev** [comment]
Can't search on the client due to missing CORS headers on openstatces.org, so we'll do it server side with two queries. Fun!

**Comment by copperwall** [comment]
Hey @jlev, if this isn't already in progress is it cool if I work on this?

**Comment by jlev** [comment]
Hey @copperwall, I did an initial implementation with the Python GraphQL library at https://github.com/OpenSourceActivismTech/call-power/commit/de0dc5bff9c336bae357a11dcae6426aae86103a

Haven't gotten around to making a new release yet, because it got mixed in with a few other features and library upgrades for v1.5.

The version at release/1.5 works in beta testing, if you're willing to be on the bleeding edge. Should have the other features slated for release done this week, if you'd rather wait.

**Comment by copperwall** [comment]
Ah okay, I'll try it out on release/1.5. Thanks!

**Comment by jlev** [comment]
released v1.5
