### ISSUE TITLE
Block list to prevent numbers from being called

### ISSUE THREAD

**Issue by mfb** [OpenSourceActivismTech/call-power#110]
Does Call Power have any block list feature, to prevent numbers from being called? It not, I think it would be a useful addition, so there's a way to prevent the tool from placing unwanted calls.

**Comment by jlev** [comment]
Hey @mfb, there is a feature to let admins block specific user phones or call requests from particular IP addresses. These can expire after a certain amount of time or be permanent. We track the number of times they get hit for reference and to ensure they're working.

This screen is available on the System page.
<img width="1169" alt="Screen Shot 2019-10-23 at 12 05 58 PM" src="https://user-images.githubusercontent.com/294964/67425794-96296580-f58d-11e9-905a-c8950d707f2e.png">

The actual blocking mechanism is at 
https://github.com/OpenSourceActivismTech/call-power/blob/master/call_server/admin/models.py#L64 and it's checked at https://github.com/OpenSourceActivismTech/call-power/blob/master/call_server/call/views.py#L349

**Comment by mfb** [comment]
oh awesome! time to upgrade :)
