### ISSUE TITLE
Keyerror : "uid" - local installation issue

### ISSUE THREAD

**Issue by nilkamal-gotarne** [OpenSourceActivismTech/call-power#120]
Hello, thank you for this open source project.
I am trying to run it on my local machine. 
I am using ubuntu 18 and python 3.7.10
When I am trying to run "flask migrate up" I am getting error - keyerror: "uid". 
I have set all the enviornment variables and followed the steps from the documentation for installation. 
Is there anything I am missing ?

**Comment by jlev** [comment]
Hi, sorry I missed this issue when you posted it. Can you reply with a specific error message and traceback?
That can help me figure out what's going on with the installation.
