### ISSUE TITLE
docker does not work out of the box

### ISSUE THREAD

**Issue by timelf123** [OpenSourceActivismTech/call-power#94]
many missing dependencies etc. any chance you experts can take a look? I'm new to python/flask and doing my best to wrap this up but have not nailed it all down yet

**Comment by jlev** [comment]
Hi Tim, thanks for trying CallPower. I deploy this application on Heroku, which doesn't use the Dockerfile, so dependencies there may indeed be out of date. However the upstream organization EFF does use Docker to deploy, and just pulled from them to reflect their changes to docker-compose.yml.example in 081d19c10cad3426b0fcccc949b7747e2cb2d51b

What error message are you getting when you are trying to run?

**Comment by timelf123** [comment]
@jlev much appreciated - I'll test out the new docker changes soon. I was able to deploy on heroku with minimal changes, thanks for that advice

**Comment by jlev** [comment]
Released in [1.4.1](https://github.com/OpenSourceActivismTech/call-power/releases/tag/v1.4.1)

**Comment by timelf123** [comment]
Have not had a chance to test the new docker changes from upstream but thank you for pulling them. Heroku was a breeze to setup

**Comment by jlev** [comment]
👍
