### ISSUE TITLE
Custom Type Is Throwing An Error

### ISSUE THREAD

**Issue by dannewoo** [OpenSourceActivismTech/call-power#98]
Hey @jlev. I just updated to the latest version of CallPower and it looks like we are having some issues with the "Custom" type option. Every time we use it we get an error that says "Sorry, this campaign is not available in your area". Any ideas as to why this could be happening and how we can fix it? Here are the errors that pop up in the logs. Thanks!

```
2018-09-13T17:03:11.925833+00:00 app[web.1]: [2018-09-13 17:03:11,925] ERROR in data_cache: Target.check_political_data_cache got unknown cached_obj type <type 'NoneType'> for key custom:wh2k61

2018-09-13T17:03:11.938039+00:00 app[web.1]: [2018-09-13 17:03:11,937] ERROR in views: No number found for target <call_server.campaign.models.Target object at 0x7f3c512bbd90>
```

**Comment by jlev** [comment]
Hey @dannewoo, it looks like some code I had that was trying to pull in updated data from the cache was incorrectly overwriting the number field in the custom targets. I've made a quick fix, and verified it works locally and on demo.callpower.org

After you merge and deploy, you may need to reset the targets phone numbers for that particular campaign before they will function correctly. Sorry for the issue, and thanks for reporting it.

**Comment by dannewoo** [comment]
Thanks @jlev how do I restart the targets phone numbers?

**Comment by dannewoo** [comment]
@jlev just figured it out. Seems to be working now. Thanks!
